### ISSUE TITLE
GPU meter

### ISSUE THREAD

**Issue by ghost** [raiguard/illustro-Gadgets#12]
Seems to be working fine except for the GPU meter. I'm on a brand new Lenovo Y700 i7 with a GTX960m Card.

What could be the problem ?

**Comment by raiguard** [comment]
For one, I am no longer developing this. It's been replaced by ModernGadgets.

You need to install and configure HWiNFO to make GPU Meter work. See the instructions in the settings skin.

But really, you should just download and use ModernGadgets instead. It's infinitely better.

**Comment by ghost** [comment]
Nice thanks !

**Comment by ghost** [comment]
The HWINFO tool thinks my GPUis0 so it thinks the ID's are wrong while the ID's are right and it should actually be GPU#1 but i can't change it ?

**Comment by raiguard** [comment]
It actually makes no difference whether it's GPU0 or GPU1. As long as the IDs are correct, it will work.

If the config took thinks they're wrong, they're probably wrong. Double-triple-quadruple check everything.
