### ISSUE TITLE
GPU METER not working

### ISSUE THREAD

**Issue by Brucbbro** [raiguard/illustro-Gadgets#9]
Hello, 
everything works out of the box, but the GPU METER keeps every value on 0, even though HWiNFO Shared Memory Viewer shows correct readings. The skin auto detected a wrong Instance id (0x14) while Shared Memory Viewer displays 0x0... Again, cpu and network are working just fine. All the Entry IDs are set correctly.
![rainmeter](https://cloud.githubusercontent.com/assets/3133958/13004939/d4f19c4c-d17e-11e5-9d99-661aad4c0ebb.jpg)

Can you get me any insight?
Thank you,
Luca

**Comment by jarnix** [comment]
I have the exact same issue. Double checked the sensor ids :(

**Comment by Gronjos** [comment]
Exaclty the same issue here. Any solution found?

**Comment by iamanai** [comment]
Woah, sorry! GitHub never told me people opened issues!

Have you enabled shared memory support in HWiNFO's settings?

**Comment by iamanai** [comment]
You also need to make sure HWiNFO's sensors are actually running. In settings, enable auto-start and "open sensors on startup" and "minimize sensors on startup".  Then open the sensors window, and minimize it. You should be good after that.

**Comment by iamanai** [comment]
Oh derp, NEVER MIND.  You have obviously already done both of those. Otherwise the SMV wouldn't be working...

 Have you tried middle clicking COU Meter to refresh it? If that doesn't work, you'll have to wait until later. I cannot diagnose it right now.

**Comment by raiguard** [comment]
Sorry for the humongous delay, GitHub never told me about this issue! If you set the corresponding IDs, it should be working.

I would middle-click GPU meter to refresh it, and see if that works. If the problem is in code, then I'm sorry, but I'm not working on illustro Gadgets anymore. I would wait for my new suite, ModernGadgets, to come out, and try that (if you want to try it now, you can find the repository on my profile page).

**Comment by Gronjos** [comment]
Thanks for the reply!
I fixed the issue. like you said, it had to do with the sensor window
closed instead of minimized.

**Comment by raiguard** [comment]
Ah, that makes sense. Let me know if you have any other questions!
